select dbms_metadata.get_ddl('TABLE','SOTCHAN1')

SELECT * FROM APTPOST1

  CREATE TABLE "RGI"."SOTCHAN1" 
   (	"CHANNEL_CODE" VARCHAR2(6 BYTE), 
	"CHANNEL_DESC" VARCHAR2(30 BYTE), 
	"CUST_CODE" VARCHAR2(10 BYTE), 
	"SEG2_CODE" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
ALTER TABLE "RGI"."SOTCHAN1" ADD PRIMARY KEY ("CHANNEL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;